# Typical laptop setup, with wifi, brightness, battery etc, for
# i3/Sway.
# For X11/i3, you'll want to replace calls to swaymsg with i3-msg, and
# the sway-xkb module with the xkb module.
# fonts we'll be re-using here and there
awesome: &awesome Font Awesome 5 Free:style=solid:pixelsize=14
awesome_brands: &awesome_brands Font Awesome 5 Brands:pixelsize=16
std_underline: &std_underline {underline: { size: 2, color: ff0000ff}}
accent: &accent 68ad6aff
background: &background 282828ff
foreground: &foreground ebdbb2ff
# This is THE bar configuration
bar:
  height: 26
  location: top
  spacing: 10
  # Default font
  font: JetBrains Mono:style=Bold:pixelsize=14
  foreground: *foreground
  background: *background
  border:
    bottom-width: 2
    color: *accent
  left:
    - label:
        content: {string: {left-margin: 10, right-margin: 10, text:  , on-click: sh -c wofi, deco: {background: {color: *accent}}}}

    - script:
        path: /home/italo/.config/yambar/scripts/disk
        args: []
        poll-interval: 300
        content: 
          - string: {text: , foreground: *accent, right-margin: 5}
          - string: {text: "{disk}"}

    - script:
        path: /home/italo/.config/yambar/scripts/cpu_usage
        args: []
        poll-interval: 3
        content: 
          - string: {text: , foreground: *accent, right-margin: 5}
          - string: {text: "{cpu_usage}"}

    - script:
        path: /home/italo/.config/yambar/scripts/memory
        args: []
        poll-interval: 3
        content: 
          - string: {text:  , foreground: *accent, right-margin: 5}
          - string: {text: "{memory}"}

  center:
    - river:
        anchors:
          - base: &river_base
              left-margin: 10
              right-margin: 10 
              tag: id 
              default: {string: {text: }}
              values:
                1: {string: {text: I}}  
                2: {string: {text: II}}  
                3: {string: {text: III}}  
                4: {string: {text: IV}}  
                5: {string: {text: V}}  
                6: {string: {text: VI}}  
                7: {string: {text: VII}}  
                8: {string: {text: VIII}}  
                9: {string: {text: IX}}  

        content:
          map:
            on-click: 
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            tag: state
            values:
              urgent:
                map:
                  <<: *river_base
              focused:
                map:
                  <<: *river_base
                  deco: 
                    background:
                      color: *accent
              visible:
                map:
                  tag: occupied
                  values:
                    false: {map: {<<: *river_base}}
                    true: {map: {<<: *river_base}}
              unfocused:
                map:
                  <<: *river_base
              invisible:
                map:
                  tag: occupied
                  values:
                    false: {empty: {}}
                    true: {map: {<<: *river_base}} #, deco: {underline: {size: 3, color: ea6962ff}}}}
  right:
    - script:
        path: /home/italo/.config/yambar/scripts/temperature
        args: []
        poll-interval: 3
        content: 
          - string: {text: , foreground: *accent, right-margin: 5}
          - string: {text: "{temperature}"}



    - removables:
        anchors:
          drive: &drive { text: , font: *awesome}
          optical: &optical {text: , font: *awesome}
        spacing: 5
        content:
          map:
            tag: mounted
            values:
              false:
                map:
                  tag: optical
                  on-click: udisksctl mount -b {device}
                  values:
                    false: [{string: *drive}, {string: {text: "{label}"}}]
                    true: [{string: *optical}, {string: {text: "{label}"}}]
              true:
                map:
                  tag: optical
                  on-click: udisksctl unmount -b {device}
                  values:
                    false:
                      - string: {<<: *drive, deco: *std_underline}
                      - string: {text: "{label}"}
                    true:
                      - string: {<<: *optical, deco: *std_underline}
                      - string: {text: "{label}"}
    - network:
        name: enp2s0
        content:
          map:
            tag: carrier
            values:
              false: {empty: {}}
              true:
                map:
                  tag: state
                  default: {string: {text: " ", font: *awesome, foreground: *accent} }
                  values:
                    up:
                      map:
                        tag: ipv4
                        default: {string: {text:  , font: *awesome, foreground: *accent}}
                        values:
                          "": {string: {text:  , font: *awesome}}
                    down:
                      map:
                        tag: ipv4
                        default: {string: {text:  睊, font: *awesome}}
                        values:
                          "": {string: {text: 睊, font: *awesome}}

    - battery:
        name: BAT0
        poll-interval: 30
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: , font: *awesome, foreground: *accent}
                      - string: {text: , font: *awesome, foreground: *accent}
                      - string: {text: , font: *awesome, foreground: *accent}
                      - string: {text: , font: *awesome, foreground: *accent}
                      - string: {text: , font: *awesome, foreground: *accent}
                      - string: {text: , font: *awesome, foreground: *accent}
                      - string: {text: , font: *awesome, foreground: *accent}
                      - string: {text: , font: *awesome, foreground: *accent}
                      - string: {text: , font: *awesome, foreground: *accent}
                      - string: {text: , font: *awesome, foreground: *accent}
                - string: {text: "{capacity}%", left-margin: 5}
        content:
          map:
            tag: state
            values:
              unknown:
                <<: *discharging
              discharging:
                <<: *discharging
              charging:
                - string: {text: , font: *awesome}
                - string: {text: "{capacity}%"}
              full:
                - string: {text: , font: *awesome}
                - string: {text: "{capacity}%"}
              not charging:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                - string: {text: "{capacity}%"}

    - script:
        path: /home/italo/.config/yambar/scripts/volume
        args: []
        poll-interval: 3
        content: 
          - string: {text: 墳, foreground: *accent}
          - string: {text: "{volume}"}

    - clock:
        time-format: "%H:%M"
        date-format: "%a %d/%m"
        content:
          - string: {text: , font: *awesome, right-margin: 5, foreground: *accent}
          - string: {text: "{date}", right-margin: 5}
          - string: {text: , font: *awesome, right-margin: 5, foreground: *accent}
          - string: {text: "{time}"}


